### ISSUE TITLE
Content of registries.yaml is not correct

### ISSUE THREAD

**Issue by bk201** [rancher/rancherd#20]
**rancherd version**: `v0.0.1-alpha13`

**To Reproduce**

Init a cluster with the following config:
```
# cat /etc/rancher/rancherd/config.yaml
role: cluster-init
token: somethingrandom
kubernetesVersion: v1.21.8+k3s1
rancherVersion: stable

registries:
  mirrors:
    docker.io:
      endpoint:
        - "http://192.168.2.106:5000"
    k8s.gcr.io:
      endpoint:
        - "http://192.168.2.106:5001"
    quay.io:
      endpoint:
        - "http://192.168.2.106:5002"
```

The generated `registries.yaml` file has content:
```
# cat /etc/rancher/k3s/registries.yaml
Auths: null
Configs: null
Mirrors:
  docker.io:
    Endpoints: null
    Rewrites: null
  k8s.gcr.io:
    Endpoints: null
    Rewrites: null
  quay.io:
    Endpoints: null
    Rewrites: null
```

If I changed the field `endpoint` to `endpoints` in the ` /etc/rancher/rancherd/config.yaml` file, the generated file will be:

```
# cat /etc/rancher/k3s/registries.yaml
Auths: null
Configs: null
Mirrors:
  docker.io:
    Endpoints:
    - http://192.168.2.106:5000
    Rewrites: null
  k8s.gcr.io:
    Endpoints:
    - http://192.168.2.106:5001
    Rewrites: null
  quay.io:
    Endpoints:
    - http://192.168.2.106:5002
    Rewrites: null
```

This seems to be correct but k3s only accepts the key `endpoint`, not `endpoints`
https://rancher.com/docs/k3s/latest/en/installation/private-registry/#mirrors

**Some investigation**

The `Endpoints` field has no ``json`` field tag: https://github.com/rancher/wharfie/blob/efd07c927031e0b324f5ce56211eea0c4a13ca06/pkg/registries/types.go#L9

And package `"sigs.k8s.io/yaml"` is used to marshal the registry, which uses `json.marshal` and converts the result to yaml https://github.com/rancher/rancherd/blob/7e9f0fe5a3fc65d1ed07744e08d831296b79fff1/pkg/registry/registry.go#L18

This might be the reason the generated file has key endpoint"s".
