### ISSUE TITLE
BootstrapResources have no effect. Should we start using Resources?

### ISSUE THREAD

**Issue by johnliu55tw** [rancher/rancherd#23]
Rancherd does not process manifests provided as `BootstrapResources` in the latest version (alpha13). Seems like it's [deprecated](https://github.com/rancher/rancherd/blob/7e9f0fe5a3fc65d1ed07744e08d831296b79fff1/pkg/config/types.go#L52). Should we turn to [`Resources`](https://github.com/rancher/rancherd/blob/7e9f0fe5a3fc65d1ed07744e08d831296b79fff1/pkg/config/types.go#L54)? When will `BootstrapResources` be removed entirely?

## Test steps
1. Create a rancherd config `/etc/rancher/rancherd/config.yaml`:
```
role: cluster-init
token: token
kubernetesVersion: v1.21.11+rke2r1
bootstrapResources:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: default
    name: bootstrap-cm
  data:
    key: helloworld
```
2. Install rancherd and start bootstrapping with `rancherd bootstrap`
3. Wait until bootstrapping finishes.
4. the bootstrap resource ConfigMap `bootstrap-cm` is not created
