### ISSUE TITLE
Can't bootstrap clusters with Rancher v2.7.5-rc2

### ISSUE THREAD

**Issue by bk201** [rancher/rancherd#30]
We can't bootstrap a cluster when integrating Rancher v2.7.5-rc2.

To reproduce:
- Change local-rke-state secret type: https://github.com/bk201/rancherd/commit/1aca2c1f6ef3051e20dfb260dfa3a3f84021bd0d
- Bump Rancher v2.6.5-rc2 in Harvester: https://github.com/bk201/harvester-installer/commits/bump-rancher-275-rc2
- Start a Harvester cluster.

## Analysis

Keep seeing this log in rancher pod:
```
│ 2023/05/30 09:10:09 [INFO] [planner] rkecluster fleet-local/local: waiting: waiting for at least one control plane, etcd, and worker node to be registered                                │
```

There is no "machine" object created.

## Rancherd bootstrap procedure:
Rancherd creates this resources after deploying Rancher chart and wait for rancher services ready.

```
---
apiVersion: v1
kind: Node
metadata:
  labels:
    node-role.kubernetes.io/etcd: "true"
  name: node1

---
apiVersion: v1
kind: Namespace
metadata:
  name: fleet-local

---
apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: local
  namespace: fleet-local
spec:
  kubernetesVersion: v1.25.9+rke2r1
  rkeConfig:
    controlPlaneConfig:
      disable:
      - rke2-snapshot-controller
      - rke2-snapshot-controller-crd
      - rke2-snapshot-validation-webhook

---
apiVersion: v1
data:
  agentToken: YWEgYmIgY2M=
  serverToken: YWEgYmIgY2M=
kind: Secret
metadata:
  name: local-rke-state
  namespace: fleet-local
type: rke.cattle.io/cluster-state

---
apiVersion: management.cattle.io/v3
kind: ClusterRegistrationToken
metadata:
  name: default-token
  namespace: local
spec:
  clusterName: local
status:
  token: aa bb cc

---
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: rancher-stable
spec:
  url: https://releases.rancher.com/server-charts/stable
```
